model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 8192
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 512
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 25001
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 0
    train:
      target: data.MedicalImageDataset
      params:
        root: 
          - <path here>
        val_images: 1000
        mode: train
        config:
          size: 512
    validation:
      target: data.MedicalImageDataset
      params:
        root: <path here>
        val_images: 1000
        mode: val
        config:
          size: 512

lightning:
  trainer:
    max_epochs: 100
    log_every_n_steps: 1000
    accumulate_grad_batches: 1
  logger: null
  modelcheckpoint: null
  callbacks: null
  pretty: null
  
